POST http://localhost:3000/akun/add
Content-Type: application/json

{
    "nama":"san",
    "email":"teswt2@gmail.com",
    "password":"12341234",
    "foto":"tes.jpg",
    "role":"ADMIN"
}
###
POST http://localhost:3000/akun/login
Content-Type: application/json

{
    "email":"te3t@gmail.com",
    "password":"12341234"
}
###
GET http://localhost:3000/akun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtYSI6InNhbiIsImVtYWlsIjoidGUzdEBnbWFpbC5jb20iLCJpYXQiOjE3MTQ3NDY4NzEsImV4cCI6MTcxNDgzMzI3MX0.9QpOTT0lh3KQP0JRoTUO6F7rtdPOlVepZfDM7nnHJ1E

###
GET http://localhost:3000/akun/token

###
DELETE  http://localhost:3000/akun/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtYSI6InNhbiIsImVtYWlsIjoidGUzdEBnbWFpbC5jb20iLCJpYXQiOjE3MTQ3NDY4NzEsImV4cCI6MTcxNDgzMzI3MX0.9QpOTT0lh3KQP0JRoTUO6F7rtdPOlVepZfDM7nnHJ1E

